### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by v-7-3** [CedrickOka/youtube-dl-api#1]
Thank you for this project
I have a question
How do I install it on server centos

**Comment by CedrickOka** [comment]
Hi,
Thanks, Yes you can use it on centos, but to help you you can use the following docker image [here](https://github.com/CedrickOka/docker-youtube-dl-api) on github or [here](https://hub.docker.com/r/cedrickoka/youtube-dl-api) on Docker hub.

If you use the Docker image, use it in combination with a web server like Nginx but you can also use the docker compose [here](https://github.com/CedrickOka/docker-compose-youtube-dl-api).

You can consult the differents docs [here](https://github.com/CedrickOka/youtube-dl-api/tree/master/docs)
